### ISSUE TITLE
Plugin crashes homebridge when MaxCube isn't online

### ISSUE THREAD

**Issue by normen** [tobsch/homebridge-platform-maxcube#1]
Hey.

First of all many thanks for putting out this homebridge plugin!

I found out that the plugin causes an error and makes the homebridge server crash on startup when the MaxCube can't be found at the specified address:

```
{ Error: connect EHOSTUNREACH 192.168.2.99:62910
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.2.99',
  port: 62910 }
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (undefined)
    at MaxCubeLowLevel.emit (events.js:163:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-lowlevel.js:51:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I am a bit of a JavaScript noob but experienced in programming so if you can point me at how to catch this error properly I can try and make a fix. As of now I seem to fail to see how this error arrives in the maxcube plugin at all..? It seems to get stuck in the maxcube library?

Cheers again for making this plugin in the first place,
Normen

**Comment by normen** [comment]
It looks like the plugin makes homebridge crash on any connection issue, see the stack traces below.

I still don't get how or where one could catch these to re-initialize the connection instead of crashing..

```
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1012:11)
    at TCP.onread (net.js:563:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (undefined)
    at MaxCubeLowLevel.emit (events.js:163:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-lowlevel.js:51:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

and

```
{ Error: connect ETIMEDOUT 192.168.2.99:62910
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.2.99',
  port: 62910 }
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (undefined)
    at MaxCubeLowLevel.emit (events.js:163:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-lowlevel.js:51:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by normen** [comment]
I added a fix for the actual crash and catch the error messages now. As we're using getConnection() to send data the plugin SHOULD reconnect if possible even if there was connection errors.

With the fix as it is now the plugin will however block HomeBridge completely when the cube isn't found when booting up HomeBridge as the callback for accessories is never fulfilled. I am working on a fix locally that should solve that issue as well.

**Comment by normen** [comment]
With the changes in the latest PR the connection is pretty solid and all errors should be caught, I tried by unplugging the Max! Cube in the middle of a connection and it simply changed the state of the "Max! Live" switch and allowed me to reconnect by switching it on again.
