### ISSUE TITLE
Node version should be 6.0.0

### ISSUE THREAD

**Issue by christoph-peters** [tobsch/homebridge-platform-maxcube#17]
Hi!

After adding MaxCube to my config file, homebridge crashes when loading. 
Any idea what could cause the error?
My config:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-777"
    },
    "platforms": [{
        "platform": "MaxCubePlatform",
        "name": "MaxCube Platform",
        "ip": "192.77.77.4",
        "port": 62910
    }
  ]
}
```

Error:

```[8/28/2017, 10:22:27 PM] Loaded plugin: homebridge-platform-maxcube
[8/28/2017, 10:22:27 PM] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
[8/28/2017, 10:22:27 PM] ---
[8/28/2017, 10:22:27 PM] Loaded config.json with 0 accessories and 1 platforms.
[8/28/2017, 10:22:27 PM] ---
[8/28/2017, 10:22:27 PM] Loading 1 platforms...
[8/28/2017, 10:22:27 PM] [MaxCube Platform] Initializing MaxCubePlatform platform...
[8/28/2017, 10:22:27 PM] [MaxCube Platform] Try connecting to Max! Cube..
Load homebridge-platform-maxcube.MaxCubePlatform
/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-commandparser.js:39
  return stringDecoder.write(Buffer.from(charArray));
                                    ^

TypeError: this is not a typed array.
    at Function.from (native)
    at decodeStringPayload (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-commandparser.js:39:37)
    at Object.parseCommandMetadata (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-commandparser.js:76:21)
    at Object.parse (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-commandparser.js:19:35)
    at MaxCubeLowLevel.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube.js:41:46)
    at emitOne (events.js:77:13)
    at MaxCubeLowLevel.emit (events.js:169:7)
    at /usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-lowlevel.js:39:14
    at Array.forEach (native)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-lowlevel.js:35:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)```

**Comment by normen** [comment]
Hm, strange.

a) What version of the plugin do you use? The one from npm or the github master?
b) Did you check if you have all updates for your actual Max! Cube installed?

**Comment by christoph-peters** [comment]
Thank you! I got it to work. I don't know too much about node, but I think in the end it was a wrong node version. According to the package.json node >= 4.4.0 should be enough, but according to [https://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha](url) "Buffer.from" was introduced in 6.0.0.

**Comment by normen** [comment]
Aight, thanks! I'll update the dependencies with the next release.
