### ISSUE TITLE
The requested platform 'MaxCubePlatform' was not registered by any plugin

### ISSUE THREAD

**Issue by nils93** [tobsch/homebridge-platform-maxcube#24]
Hey, 
I'm receiving an error when I want to start homebridge after following the guided readme... 
Node is on 6.10.0 and npm on 3.10.10 

This is the full error report after typing "homebridge" and hitting enter:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/24/2017, 12:15:29 AM] Loaded plugin: homebridge-rfoutlets
[11/24/2017, 12:15:29 AM] Registering accessory 'homebridge-rfoutlets.RFOutlet'
[11/24/2017, 12:15:29 AM] ---
[11/24/2017, 12:15:29 AM] Loaded config.json with 3 accessories and 1 platforms.
[11/24/2017, 12:15:29 AM] ---
[11/24/2017, 12:15:29 AM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'MaxCubePlatform' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

I really appreciate any help to get rid of this error!

**Comment by normen** [comment]
Please re-read the manual and check if you installed the plugin right. Please note that this is not a support forum but a bug tracker. We cannot give support for this free software, you are on your own.
