### ISSUE TITLE
HomeKit doesn't show all thermostats 

### ISSUE THREAD

**Issue by Calprainn** [tobsch/homebridge-platform-maxcube#4]
Hello,

first of all many thanks for your work (@tobsch)!! I using homebridge over a year now and I hoped someone will bring a plugin for the MAX! Cube system. 

But I get some issues with the intergration of my existing devices. Just two of my eight installed thermostats are visible in the Homekit environment.

Any ideas?

**Comment by normen** [comment]
Did you try downloading the latest version from github? I changed A LOT of things about the plugin just yesterday, thats not in NPMJS yet.

**Comment by Calprainn** [comment]
Oh, no. I downloaded the plugin over NPM. I'll test the updated git version after work and will report! :)

**Comment by Calprainn** [comment]
I remove the homebridge-platform-maxcube folder in "/usr/local/lib/node_modules/homebridge/node_modules" and I cloned the git respo. With "npm install" the plugin. After starting the homebridge, I got the same issue. Just two devices responded.

So I remove the maxcube folder and installed the plugin via "npm i homebridge-platform-maxcube" and this is my log after restart the homebridge:

`root@UBUNTU:/usr/local/lib/node_modules/homebridge/node_modules# homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-6-8 17:15:53] Loaded plugin: homebridge-platform-maxcube
[2017-6-8 17:15:53] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
[2017-6-8 17:15:53] ---
[2017-6-8 17:15:53] Loaded config.json with 0 accessories and 1 platforms.
[2017-6-8 17:15:53] ---
[2017-6-8 17:15:53] Loading 1 platforms...
[2017-6-8 17:15:53] [MaxCube Platform] Initializing MaxCubePlatform platform...
[2017-6-8 17:15:53] [MaxCube Platform] Connecting to MaxCube
[2017-6-8 17:15:53] [MaxCube Platform] Fetching maxCube devices.
Load homebridge-platform-maxcube.MaxCubePlatform
[2017-6-8 17:15:53] [MaxCube Platform] Connected
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0f57f8
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 11606a
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 11603e
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 14e6a9
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 08de4c
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0c6d3c
[2017-6-8 17:15:54] [MaxCube Platform] registering device { rf_address: '0c6d3c',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'MANUAL',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 0,
  setpoint: 22,
  temp: 0 } { device_type: 1,
  device_name: 'Thermostat 1',
  room_name: 'Büro',
  room_id: 1 }
[2017-6-8 17:15:54] [MaxCube Platform] adding device: 0c6d3c
[2017-6-8 17:15:54] [MaxCube Platform] setting temp to off  0
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 10036e
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0b2f07
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 08da02
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0f572a
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0de9a2
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 097107
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0df083
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0971c9
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 1001d8
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 1000f4
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0c6d34
[2017-6-8 17:15:54] [MaxCube Platform] registering device { rf_address: '0c6d34',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 0,
  setpoint: 22,
  temp: 0 } { device_type: 1,
  device_name: 'Thermostat 1',
  room_name: 'Bad',
  room_id: 2 }
[2017-6-8 17:15:54] [MaxCube Platform] adding device: 0c6d34
[2017-6-8 17:15:54] [MaxCube Platform] setting temp to off  0
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0d6430
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 1161a4
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0f5731
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0df151
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0f554f
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0d65c5
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] gegting device info for 0d6674
[2017-6-8 17:15:54] [MaxCube Platform] ignoring non thermostat device
[2017-6-8 17:15:54] [MaxCube Platform] Initializing platform accessory 'Thermostat 1 (Büro)'...
[2017-6-8 17:15:54] [MaxCube Platform] Initializing platform accessory 'Thermostat 1 (Bad)'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[2017-6-8 17:15:54] Homebridge is running on port 51824.
`
When I try to change the temparature of these two thermostate, homebridge responce of my input but the thermostate do not react.

**Comment by normen** [comment]
The NPM version only allowed me to set the temperature maybe once, then it loses connection. You should go on trying with the git version.

About your issue, maybe try outputting the device info for the rejected devices (i.e. log("device info", device, deviceInfo);) in the index.js file. It looks like it rejects a lot of devices, it could be that its due to you using another version of the thermostat devices. Do you use a mixed setup of normal and "basic" thermostats?

**Comment by Calprainn** [comment]
I reinstall the actually github version and my two connected thermostat are now react to my commands.

In the past I tried some other home automatic systems like openhab, fhem and pimatic. In one of them I read a device descriptions something like "Thermostat Plus". When I check my thermostats I can't see any diffence between them. Maybe there a different versions of the internal firmware.

The list of the rejected devices is just so long because I have beside my thermostats some window sensors and wall thermostats.

How can I outputting the device info in the index.js file? My java programming skills are very low. ;-)

**Comment by normen** [comment]
There is a commented out line in index.js:
`//that.log('ignoring non thermostat device');`

replace that with
`that.log('ignoring non thermostat device', device, deviceInfo);`

and then post the startup log here.

Thank you very much, given your elaborate setup this will help improving the plugin a lot.

**Comment by Calprainn** [comment]
You're welcome. It's my pleasure to help you guys to further develop the plugin.

Here is my log after editing:

> root@UBUNTU:/usr/local/lib/node_modules/homebridge/node_modules/homebridge-platform-maxcube# homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-6-8 19:02:42] Loaded plugin: homebridge-platform-maxcube
[2017-6-8 19:02:42] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
[2017-6-8 19:02:42] ---
[2017-6-8 19:02:42] Loaded config.json with 0 accessories and 1 platforms.
[2017-6-8 19:02:42] ---
[2017-6-8 19:02:42] Loading 1 platforms...
[2017-6-8 19:02:42] [MaxCube Platform] Initializing MaxCubePlatform platform...
Load homebridge-platform-maxcube.MaxCubePlatform
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0f57f8' } { device_type: 4,
  device_name: 'Balkontürkontakt 1',
  room_name: 'Küche',
  room_id: 9 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '11606a',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 0,
  setpoint: 20,
  temp: 0 } { device_type: 2,
  device_name: 'Thermostat 1',
  room_name: 'Schlafzimmer',
  room_id: 8 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '11603e',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: true,
  link_error: false,
  battery_low: false,
  valve: 43,
  setpoint: 21,
  temp: 21.7 } { device_type: 2,
  device_name: 'Thermostat 1',
  room_name: 'Küche',
  room_id: 9 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '14e6a9',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 1,
  setpoint: 12,
  temp: 0 } { device_type: 3,
  device_name: 'Wandthermostat',
  room_name: 'Kind Schlafzimmer',
  room_id: 3 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '08de4c',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 0,
  setpoint: 12,
  temp: 0 } { device_type: 2,
  device_name: 'Kind Schlaf',
  room_name: 'Kind Schlafzimmer',
  room_id: 3 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '10036e',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'MANUAL',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 4,
  setpoint: 23,
  temp: 0 } { device_type: 3,
  device_name: 'Wandthermostat 1',
  room_name: 'Bad',
  room_id: 2 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0b2f07' } { device_type: 5,
  device_name: 'Eco Taster 1',
  room_name: null,
  room_id: null }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '08da02',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 0,
  setpoint: 20,
  temp: 0 } { device_type: 2,
  device_name: 'Kind Bad',
  room_name: 'Kind Bad',
  room_id: 4 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0f572a' } { device_type: 4,
  device_name: 'Fensterkontakt 1',
  room_name: 'Kind Bad',
  room_id: 4 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0de9a2',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 0,
  setpoint: 22,
  temp: 0 } { device_type: 2,
  device_name: 'Thermostat 2',
  room_name: 'Wohnzimmer',
  room_id: 5 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '097107',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 4,
  setpoint: 20,
  temp: 0 } { device_type: 3,
  device_name: 'Wandthermostat 1',
  room_name: 'Schlafzimmer',
  room_id: 8 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0df083',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'MANUAL',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 100,
  setpoint: 22,
  temp: 0 } { device_type: 2,
  device_name: 'Thermostat 1',
  room_name: 'Esszimmer',
  room_id: 6 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0971c9',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 4,
  setpoint: 20,
  temp: 0 } { device_type: 3,
  device_name: 'Wandthermostat 1',
  room_name: 'Kind Bad',
  room_id: 4 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '1001d8',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 4,
  setpoint: 21,
  temp: 0 } { device_type: 3,
  device_name: 'Wandthermostat 1',
  room_name: 'Büro',
  room_id: 1 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '1000f4',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 4,
  setpoint: 22,
  temp: 0 } { device_type: 3,
  device_name: 'Wandthermostat 1',
  room_name: 'Wohnzimmer',
  room_id: 5 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0d6430' } { device_type: 4,
  device_name: 'Fensterkontakt 1',
  room_name: 'Bad',
  room_id: 2 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '1161a4',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 0,
  setpoint: 17,
  temp: 0 } { device_type: 2,
  device_name: 'Thermostat 1',
  room_name: 'Flur',
  room_id: 7 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0f5731' } { device_type: 4,
  device_name: 'Fensterkontakt 1',
  room_name: 'Schlafzimmer',
  room_id: 8 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0df151',
  initialized: true,
  fromCmd: false,
  error: false,
  valid: true,
  mode: 'AUTO',
  dst_active: true,
  gateway_known: true,
  panel_locked: false,
  link_error: false,
  battery_low: false,
  valve: 0,
  setpoint: 22,
  temp: 0 } { device_type: 2,
  device_name: 'Thermostat 1',
  room_name: 'Wohnzimmer',
  room_id: 5 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0f554f' } { device_type: 4,
  device_name: 'Fensterkontakt 1',
  room_name: 'Wohnzimmer',
  room_id: 5 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0d65c5' } { device_type: 4,
  device_name: 'Fensterkontakt 1',
  room_name: 'Kind Schlafzimmer',
  room_id: 3 }
[2017-6-8 19:02:43] [MaxCube Platform] ignoring non thermostat device { rf_address: '0d6674' } { device_type: 4,
  device_name: 'Fensterkontakt 1',
  room_name: 'Büro',
  room_id: 1 }
[2017-6-8 19:02:43] [MaxCube Platform] Initializing platform accessory 'Thermostat 1 (Büro)'...
[2017-6-8 19:02:43] [MaxCube Platform] Initializing platform accessory 'Thermostat 1 (Bad)'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
    ┌────────────┐
    │ 031-45-154 │
    └────────────┘
[2017-6-8 19:02:43] Homebridge is running on port 51824.

**Comment by normen** [comment]
Okay, as I expected its simply another type of thermostat. The number "2" should be accepted as well.

I will add a fix to my fork (https://github.com/normen/homebridge-platform-maxcube) and make a PR for @tobsch when I'm home. Hopefully he'll also publish the updated plugin to NPMJS in a few days.

If you want you can also try to fix it locally yourself until I'm home, simply make the check for 1 and 2 instead of only 1. That should work right away as the thermostat devices both supply the same data.

**Comment by normen** [comment]
I actually added the fix via the github web client, if you want you can try the version here:

https://github.com/normen/homebridge-platform-maxcube

**Comment by normen** [comment]
Thinking about it we should try if the wall thermostat devices (3) also make sense in HomeKit. The way it looks they should work the same for the plugin, question is if it makes sense to control them and what happens when both the wall thermostat and the thermostat devices get a signal.

The other way around if we don't add them then maybe things get mixed up - HomeKit sets a temperature for the thermostat and the wall thermostat also sets a temperature?

If you could be so kind and try which version is better? If you change the line
`if (deviceInfo.device_type == 1||deviceInfo.device_type == 2)`
to
`if (deviceInfo.device_type == 1||deviceInfo.device_type == 2||deviceInfo.device_type == 3)`
you'll get both thermostat and wall thermostat devices in HomeKit

**Comment by Calprainn** [comment]
I cp your index.js into my environment and it works! Homebridge integrate all thermostat. Great job! :)

About the wall thermostat: even when you sets the thermostat temparature, the wall thermostat also sets. I don't think it make sense to fetsch the wall thermostat into homekit!? Just like the window sensors.

**Comment by Calprainn** [comment]
Unfortunately, I have been happy too early... With your fix, Homebridge fetching the missing devices and Homekit also show them but in Homekit they don't react ("No answer"). Some seconds later homebridge crashes:

> { Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (undefined)
    at MaxCubeLowLevel.emit (events.js:163:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/homebridge-platform-maxcube/node_modules/maxcube/maxcube-lowlevel.js:51:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by normen** [comment]
Okay, cool! I was not sure about the wall thermostat devices as I don't have any. You say when you set all thermostat devices in a room via HomeKit then the wall thermostat automatically displays that value as well? Then its cool. When you set the thermostat devices via the wall panel (or directly on the thermostat) then homekit should also get the new values after a minute or so.

Thank you very much for helping! Feel free to add any additional feedback or things you think could be improved while you use the plugin!

About the error: Did you have your Max! software connected at the same time? You can't connect using HomeBridge when Max is running and vice versa. The error is a connection error - can happen because of anything network really (e.g. MaxCube is offline) but also happens when the Max software is already connected.

Its kind of hard to catch these errors with the maxcube library we're using, normally they shouldn't happen or at least they shouldn't crash the plugin.

**Comment by Calprainn** [comment]
>  You say when you set all thermostat devices in a room via HomeKit then the wall thermostat automatically displays that value as well? Then its cool. When you set the thermostat devices via the wall panel (or directly on the thermostat) then homekit should also get the new values after a minute or so.

This is how the work. They are coupled in the MAX Software. And Homekit also knows no commands to control them.

> About the error: Did you have your Max! software connected at the same time? You can't connect using HomeBridge when Max is running and vice versa - the same is true for th Max! internet/smart phone connection.

Okay, thats it. The internet remote setting is on. Unfortunately my wife and kid have android devices. Now I have to look how I give them access to the heating control without Homekit (and no MAX internet remote control)...

**Comment by normen** [comment]
Okay, I will see how we can work around that issue, wonder why the connection fails though, maybe its because you have so many devices and they all get checked? Does it always fail and always about the same time?

I do have an idea about how to avoid the whole homebridge crashing but that the connection breaks up in the first place isn't good..

**Comment by Calprainn** [comment]
Something funny has happened: yesterday I spend the whole day to realize this MAX-Control-Homekit thing with pimatic and I always got an error with the homekit plugin. Today I found this homebridge plugin. But now I restarted my Linux server and pimatic runs like a charm with the Homekit plugin (and my MAX thermostats). I think I'll use pimatic. There is a webinterface to control my MAX Cube over pimatic (with DynDNS) and w/o a connection to the MAX provider server. This is much easier for my wife and kid to control the heating with their android devices.

But I think today we have achieved a lot for this homebridge plugin! :)

**Comment by normen** [comment]
Alright, thank you very much anyway, that was very helpful!

**Comment by normen** [comment]
In case you get issues with your other setup or get back to this, the connection crash should be fixed in github. Would be interesting to know if it also manages to reconnect properly in your case but I suppose you had enough of playing with HomeBridge for now :)

**Comment by Calprainn** [comment]
Actually I am quite satisfied with the pimatic environment. I have just ordered a radio modul to control my garage door now. :D 

I'll test your updated code later and will report. I got a thought about my connection crash: perhaps the pimatic systems ran beside and maybe thats the reason why homebridge collaps after all.

**Comment by normen** [comment]
Oh, that would be a really good reason, that could be. In that case please do run it with pimatic activated so we can test the robustness of the current setup. It will still halt HomeBridge if the cube can't be found during startup but if the connection drops later it should recover - or at least not crash HomeBridge.

**Comment by normen** [comment]
I'm closing this issue as the original issue was fixed.
